[CmdletBinding()]
param(
    [string]$Output = (Join-Path $PSScriptRoot '..\esp32\display-controller\main\generated_layer_labels.h')
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$labels = @('BASE', 'SYM', 'NAV', 'CAD', 'ADJ')
$font = [Drawing.Font]::new('Noto Sans JP Black', 42, [Drawing.FontStyle]::Regular,
                            [Drawing.GraphicsUnit]::Pixel)
$format = [Drawing.StringFormat]::GenericTypographic.Clone()
$format.FormatFlags = $format.FormatFlags -bor [Drawing.StringFormatFlags]::NoWrap
$entries = [Collections.Generic.List[object]]::new()

try {
    foreach ($label in $labels) {
        $bitmap = [Drawing.Bitmap]::new(300, 80, [Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $graphics = [Drawing.Graphics]::FromImage($bitmap)
        try {
            $graphics.Clear([Drawing.Color]::Transparent)
            $graphics.TextRenderingHint = [Drawing.Text.TextRenderingHint]::AntiAliasGridFit
            $graphics.DrawString($label, $font, [Drawing.Brushes]::White, 4, 0, $format)

            $minX = $bitmap.Width
            $minY = $bitmap.Height
            $maxX = -1
            $maxY = -1
            for ($y = 0; $y -lt $bitmap.Height; $y++) {
                for ($x = 0; $x -lt $bitmap.Width; $x++) {
                    if ($bitmap.GetPixel($x, $y).A -ne 0) {
                        if ($x -lt $minX) { $minX = $x }
                        if ($y -lt $minY) { $minY = $y }
                        if ($x -gt $maxX) { $maxX = $x }
                        if ($y -gt $maxY) { $maxY = $y }
                    }
                }
            }
            if ($maxX -lt $minX -or $maxY -lt $minY) {
                throw "Font renderer produced an empty label for $label."
            }
            $width = $maxX - $minX + 1
            $height = $maxY - $minY + 1
            $alpha = [byte[]]::new($width * $height)
            for ($y = 0; $y -lt $height; $y++) {
                for ($x = 0; $x -lt $width; $x++) {
                    $alpha[$y * $width + $x] = $bitmap.GetPixel($minX + $x, $minY + $y).A
                }
            }
            $entries.Add([pscustomobject]@{
                Label = $label
                Symbol = $label.ToLowerInvariant()
                Width = $width
                Height = $height
                Alpha = $alpha
            })
        }
        finally {
            $graphics.Dispose()
            $bitmap.Dispose()
        }
    }
}
finally {
    $format.Dispose()
    $font.Dispose()
}

$builder = [Text.StringBuilder]::new()
$null = $builder.AppendLine('/* Generated by tools/generate_esp_layer_labels.ps1. */')
$null = $builder.AppendLine('#pragma once')
$null = $builder.AppendLine('#include <stdint.h>')
$null = $builder.AppendLine('struct merry_layer_label {')
$null = $builder.AppendLine('    const char *name;')
$null = $builder.AppendLine('    uint16_t width;')
$null = $builder.AppendLine('    uint16_t height;')
$null = $builder.AppendLine('    const uint8_t *alpha;')
$null = $builder.AppendLine('};')

foreach ($entry in $entries) {
    $null = $builder.AppendLine("static const uint8_t merry_layer_$($entry.Symbol)[] = {")
    for ($offset = 0; $offset -lt $entry.Alpha.Length; $offset += 16) {
        $count = [Math]::Min(16, $entry.Alpha.Length - $offset)
        $values = for ($index = 0; $index -lt $count; $index++) {
            '0x{0:x2}' -f $entry.Alpha[$offset + $index]
        }
        $null = $builder.AppendLine('    ' + ($values -join ', ') + ',')
    }
    $null = $builder.AppendLine('};')
}

$null = $builder.AppendLine('static const struct merry_layer_label merry_layer_labels[] = {')
foreach ($entry in $entries) {
    $null = $builder.AppendLine(
        "    {`"$($entry.Label)`", $($entry.Width), $($entry.Height), merry_layer_$($entry.Symbol)},"
    )
}
$null = $builder.AppendLine('};')

$resolved = [IO.Path]::GetFullPath($Output)
[IO.File]::WriteAllText($resolved, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Generated $resolved with $($entries.Count) antialiased labels."
